### ISSUE TITLE
Compiler can not find the packages path.

### ISSUE THREAD

**Issue by Zony-Zhao** [keijiro/NoiseShader#11]
I install as readme file directed.
![image](https://user-images.githubusercontent.com/50739849/160406034-26e12a24-0b7f-4815-8249-2a400bbf90d6.png)
But I can not include this in a URP shader. Is there anything changed in these versions?

**Comment by keijiro** [comment]
You don't need `@2.0.0`. See [this](https://github.com/keijiro/NoiseShader/blob/master/Assets/Visualizer.shader#L19).

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.

**Comment by Zony-Zhao** [comment]
![image](https://user-images.githubusercontent.com/50739849/160410820-e928d8c2-d0f3-44b5-b2dc-7813f909ecac.png)
em...Doesn't seem to be this problem. I have tried quite a few packages names.
Is there anything I can do to help solve this?

**Comment by keijiro** [comment]
Please copy-paste the error message.

**Comment by Zony-Zhao** [comment]
Solved. It seems to be Rider have trouble with indexing the package with manually install/scoped registry. The package works well.
