### ISSUE TITLE
Noise not working in built executable

### ISSUE THREAD

**Issue by Avokadoen** [keijiro/NoiseShader#6]
I have this line in a compute shader:
```glsl
#include "Packages/jp.keijiro.noiseshader/Shader/ClassicNoise3D.hlsl"
// ...
// cnoise have range [-1, 1], but noise should be in range [0, 1]
float noise = (cnoise(float3(tilePos * NoiseScale, Seed)) + 1) * 0.5;
set = noise >= SetThreshold;
```

I get the following when running in the editor:

![Capture](https://user-images.githubusercontent.com/26302304/104909329-fa50fa00-5987-11eb-85c1-97e807145648.PNG)

When attempting to build and run a standalone executable I get the following:

![image](https://user-images.githubusercontent.com/26302304/104909456-2bc9c580-5988-11eb-88c1-12fec784065c.png)

**Comment by Avokadoen** [comment]
Same story with the i.e ``snoise``

**Comment by keijiro** [comment]
Could you provide a minimal project that reproduces the issue?

**Comment by Avokadoen** [comment]
> 
> 
> Could you provide a minimal project that reproduces the issue?

Sure 👍

**Comment by Avokadoen** [comment]
After some investigation and failing to recreate a minimal project to reproduce the bug I discovered that the bug must be in our project code. Changing our line ``float noise = (snoise(seed) + 1) * 0.5;`` to ``float noise = 0`` still results in the  texture being filled with set pixels in the build. 

My apologies. Should have been less trigger happy with reporting this issue 😞

**Comment by Avokadoen** [comment]
For anyone curious, the problem was caused by only sending some shader values in [OnValidate](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnValidate.html)
