### ISSUE TITLE
Range of SimplexNoise3D.glsl

### ISSUE THREAD

**Issue by Tuntenfisch** [keijiro/NoiseShader#7]
Hello,

I was wondering what the returned range of `float snoise(vec3 v)` is. Is it [-1, 1] like mentioned in http://weber.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf?

**Comment by keijiro** [comment]
Unfortunately, I don't have any mathematically firm idea about it. Maybe yes, but not sure. I'd recommend testing it before you make the assumption on it.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
